### PR TITLE
Bug 1532743 - Do not reset z-index to auto

### PR DESCRIPTION
**Pull request by josejulio**

### CODE REVIEW

**Comment by josejulio** [comment]
@burmanm could you review? This goes directly into release/jon3.3.x

**Comment by burmanm** [comment]
Why the direct? Is there such a big difference compared to the master?

**Comment by josejulio** [comment]
The css rule i want to remove is no longer in master: https://github.com/rhq-project/rhq/blob/master/modules/enterprise/gui/coregui/src/main/webapp/org.rhq.coregui.CoreGUI/sc/skins/CoreGUI/skin_styles.css#L23

**Comment by burmanm** [comment]
Why wasn't that commit dc2fd398e11f2588ac43c6e84bb35f8b95e3ef33 just cherry-picked? Or this modification for a cherry-pick?

**Comment by josejulio** [comment]
That commit (https://github.com/rhq-project/rhq/commit/dc2fd398e11f2588ac43c6e84bb35f8b95e3ef33) was cherry-picked, this is a follow-up. I'm removing a code that is only on this branch.

**Pull request merged**
