### PR TITLE
[BZ-1448500] Remove/ignore unused properties for servlet on profile=l…

### PR DESCRIPTION
**Pull request by josejulio**
…oad-balancer

  Ignore setting=jsp/websocket when loading data.
  Remove setting=jsp/websocket when updating data.
  Add "(Not used by load-balancer)" on display name for setting=jsp/websocket.

@burmanm could you take a look?

### CODE REVIEW

**Comment by burmanm** [comment]
Does this still work with EAP7 also?

**Comment by josejulio** [comment]
It should! Let me test.

**Comment by josejulio** [comment]
It does work.
I'm querying the resource to know if it has the setting=jsp and setting=websocket properties, if they are found everything goes as usual. 
The ones that aren't found are removed (the whole group, e.g. all setting=jsp/*)

**Comment by loleary** [comment]
Why not leave the label intact and just use a special value to indicate its not used?

For example, on configuration read, if the property is not supported (i.e. load-balancer profile) then the value returned could be "*** not used by load-balancer ***". Even if the user changes the value and saves it, it would be ignored and the control would have its value updated to "*** not used by load-balancer ***".

This prevents hard-coding the control's display name to include a profile that could later change or be expanded.

Regardless, the approach you are taking seems to be the right one form my point-of-view.

**Comment by josejulio** [comment]
@loleary I like that idea. I recall that most fields were booleans, but will double check and see the idea fits well there.

**Comment by josejulio** [comment]
@burmanm I did @loleary suggestions.
Could you please review?

**Pull request merged**
