### PR TITLE
Bug 1246083 - CLI operations don't work when Native Local Authentication is enabled and Native management API host is set to 0.0.0.0

### PR DESCRIPTION
**Pull request by tsegismont**
Removed nativeHost and nativePort settings from EAP7 servers config, as
the CLI now connects to the HTTP management port.

Updated discovery classes so that when '0.0.0.0' is discovered,
'127.0.0.1' is used
Updated component classes to log a warning if native/management host is set to
'0.0.0.0'
Changed defaults from 'localhost' to '127.0.0.1' in HostConfiguration
classes to avoid troubles when localhost is configured to something else
than loopback address

Note that, with these changes, new servers bound to '0.0.0.0' will no
longer have this address in the resource name, but '127.0.0.1' instead.
Resource keys are not impacted. Already inventoried EAP6 resources are left
untouched.

### CODE REVIEW

**Comment by tsegismont** [comment]
Please do not merge yet. I need to make sure this works fine in domain mode as well.

**Comment by burmanm** [comment]
I think native host / native port were correctly working in domain mode, but not in standalone, so check that part..

**Comment by tsegismont** [comment]
Le 15/03/2016 19:40, Michael Burman a écrit :
> I think native host / native port were correctly working in domain mode,
> but not in standalone, so check that part.

They didn't in standalone mode just because the native interface is no 
longer bound by default.
The CLI used to connect over the native interface but now it connects 
over HTTP with upgrade to remoting protocol.
As we introduced nativeHost and nativeHost just for CLI with localAuth 
mode, I believe we shouldn't keep these attributes any more. I verified 
that localAuth mode works on a standalone server with http upgrade, now 
I need to verify it does with a domain controller as well.

**Comment by tsegismont** [comment]
@burmanm just verified, localAuth works fine as well with a domain controller and http ugrade to remoting

**Comment by tsegismont** [comment]
Rebased on master

**Comment by tsegismont** [comment]
Closing because we are going to separate this PR in two parts: one for EAP6 plugin, one for EAP7 plugin.

**Pull request closed without merging**
