### PR TITLE
Bug 1650478 - Remove handoff-executor from long/short running threads

### PR DESCRIPTION
**Pull request by josejulio**
EAP 6 related

### CODE REVIEW

**Comment by burmanm** [comment]
Before merging.. did this really apply to all versions of EAP 6? And not just later ones?

**Comment by loleary** [comment]
It does not. I can see that this attribute was in EAP 6.0... Not sure what version removed it but we will need to support all minor versions.

**Comment by josejulio** [comment]
EAP 6.2 and 6.4 have this attribute, but if you set it it asks for a "reload". Upon reloading the EAP instance crash and you need to manually edit (to remove) the handoff-executor. The XSD, I'll check on EAP 6.0 when i'm back on monday.

```
13:20:41,963 ERROR [org.jboss.as.server] (Controller Boot Thread) JBAS015956: Caught exception during boot: org.jboss.as.controller.persistence.ConfigurationPersistenceException: JBAS014676: Failed to parse configuration
        at org.jboss.as.controller.persistence.XmlConfigurationPersister.load(XmlConfigurationPersister.java:141) [jboss-as-controller-7.3.4.Final-redhat-1.jar:7.3.4.Final-redhat-1]
        at org.jboss.as.server.ServerService.boot(ServerService.java:324) [jboss-as-server-7.3.4.Final-redhat-1.jar:7.3.4.Final-redhat-1]
        at org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:253) [jboss-as-controller-7.3.4.Final-redhat-1.jar:7.3.4.Final-redhat-1]
        at java.lang.Thread.run(Thread.java:748) [rt.jar:1.8.0_201]
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[243,21]
Message: JBAS014789: Unexpected element '{urn:jboss:domain:jca:1.1}handoff-executor' encountered
        at org.jboss.as.controller.parsing.ParseUtils.unexpectedElement(ParseUtils.java:86) [jboss-as-controller-7.3.4.Final-redhat-1.jar:7.3.4.Final-redhat-1]
        at org.jboss.as.threads.ThreadsParser.parseBoundedQueueThreadPool1_1(ThreadsParser.java:439)
        at org.jboss.as.threads.ThreadsParser.parseBlockingBoundedQueueThreadPool(ThreadsParser.java:258)
        at org.jboss.as.connector.subsystems.jca.JcaExtension$ConnectorSubsystemParser.parseWorkManager(JcaExtension.java:409)
        at org.jboss.as.connector.subsystems.jca.JcaExtension$ConnectorSubsystemParser.readElement(JcaExtension.java:257)
        at org.jboss.as.connector.subsystems.jca.JcaExtension$ConnectorSubsystemParser.readElement(JcaExtension.java:112)
        at org.jboss.staxmapper.XMLMapperImpl.processNested(XMLMapperImpl.java:110) [staxmapper-1.1.0.Final-redhat-2.jar:1.1.0.Final-redhat-2]
        at org.jboss.staxmapper.XMLExtendedStreamReaderImpl.handleAny(XMLExtendedStreamReaderImpl.java:69) [staxmapper-1.1.0.Final-redhat-2.jar:1.1.0.Final-redhat-2]
        at org.jboss.as.server.parsing.StandaloneXml.parseServerProfile(StandaloneXml.java:1024) [jboss-as-server-7.3.4.Final-redhat-1.jar:7.3.4.Final-redhat-1]
        at org.jboss.as.server.parsing.StandaloneXml.readServerElement_1_4(StandaloneXml.java:458) [jboss-as-server-7.3.4.Final-redhat-1.jar:7.3.4.Final-redhat-1]
        at org.jboss.as.server.parsing.StandaloneXml.readElement(StandaloneXml.java:145) [jboss-as-server-7.3.4.Final-redhat-1.jar:7.3.4.Final-redhat-1]
        at org.jboss.as.server.parsing.StandaloneXml.readElement(StandaloneXml.java:107) [jboss-as-server-7.3.4.Final-redhat-1.jar:7.3.4.Final-redhat-1]
        at org.jboss.staxmapper.XMLMapperImpl.processNested(XMLMapperImpl.java:110) [staxmapper-1.1.0.Final-redhat-2.jar:1.1.0.Final-redhat-2]
        at org.jboss.staxmapper.XMLMapperImpl.parseDocument(XMLMapperImpl.java:69) [staxmapper-1.1.0.Final-redhat-2.jar:1.1.0.Final-redhat-2]
        at org.jboss.as.controller.persistence.XmlConfigurationPersister.load(XmlConfigurationPersister.java:133) [jboss-as-controller-7.3.4.Final-redhat-1.jar:7.3.4.Final-redhat-1]
        ... 3 more

13:20:41,965 FATAL [org.jboss.as.server] (Controller Boot Thread) JBAS015957: Server boot has failed in an unrecoverable manner; exiting. See previous messages for details.

```

**Comment by josejulio** [comment]
I couldn't run EAP 6.0 in standalone but when trying to set this property in domain mode froze the cli (i suppose it was waiting for a response).

I then proceed to add it to the XML and got a similar response:
```
stenceException: JBAS014676: Failed to parse configuration
[Host Controller]       at org.jboss.as.controller.persistence.XmlConfigurationPersister.load(XmlConfigurationPersister.java:141) [jboss-as-controller-7.1.2.Final-redhat-1.jar:7.1.2.Final-redhat-1]
[Host Controller]       at org.jboss.as.host.controller.DomainModelControllerService.boot(DomainModelControllerService.java:440) [jboss-as-host-controller-7.1.2.Final-redhat-1.jar:7.1.2.Final-redhat-1]
[Host Controller]       at org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:156) [jboss-as-controller-7.1.2.Final-redhat-1.jar:7.1.2.Final-redhat-1]
[Host Controller]       at java.lang.Thread.run(Thread.java:748) [rt.jar:1.8.0_201]
[Host Controller] Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[161,25]
[Host Controller] Message: JBAS014789: Unexpected element '{urn:jboss:domain:jca:1.1}handoff-executor' encountered
[Host Controller]       at org.jboss.as.controller.parsing.ParseUtils.unexpectedElement(ParseUtils.java:85) [jboss-as-controller-7.1.2.Final-redhat-1.jar:7.1.2.Final-redhat-1]
[Host Controller]       at org.jboss.as.threads.ThreadsParser.parseBoundedQueueThreadPool1_1(ThreadsParser.java:440) [jboss-as-threads-7.1.2.Final-redhat-1.jar:7.1.2.Final-redhat-1]
[Host Controller]       at org.jboss.as.threads.ThreadsParser.parseBlockingBoundedQueueThreadPool(ThreadsParser.java:259) [jboss-as-threads-7.1.2.Final-redhat-1.jar:7.1.2.Final-redhat-1]
[Host Controller]       at org.jboss.as.connector.subsystems.jca.JcaExtension$ConnectorSubsystemParser.parseWorkManager(JcaExtension.java:476)
[Host Controller]       at org.jboss.as.connector.subsystems.jca.JcaExtension$ConnectorSubsystemParser.readElement(JcaExtension.java:324)
[Host Controller]       at org.jboss.as.connector.subsystems.jca.JcaExtension$ConnectorSubsystemParser.readElement(JcaExtension.java:176)
[Host Controller]       at org.jboss.staxmapper.XMLMapperImpl.processNested(XMLMapperImpl.java:110) [staxmapper-1.1.0.Final-redhat-1.jar:1.1.0.Final-redhat-1]
[Host Controller]       at org.jboss.staxmapper.XMLExtendedStreamReaderImpl.handleAny(XMLExtendedStreamReaderImpl.java:69) [staxmapper-1.1.0.Final-redhat-1.jar:1.1.0.Final-redhat-1]
[Host Controller]       at org.jboss.as.host.controller.parsing.DomainXml.parseProfiles(DomainXml.java:735) [jboss-as-host-controller-7.1.2.Final-redhat-1.jar:7.1.2.Final-redhat-1]
[Host Controller]       at org.jboss.as.host.controller.parsing.DomainXml.readDomainElement1_3(DomainXml.java:340) [jboss-as-host-controller-7.1.2.Final-redhat-1.jar:7.1.2.Final-redhat-1]
[Host Controller]       at org.jboss.as.host.controller.parsing.DomainXml.readElement(DomainXml.java:130) [jboss-as-host-controller-7.1.2.Final-redhat-1.jar:7.1.2.Final-redhat-1]
[Host Controller]       at org.jboss.as.host.controller.parsing.DomainXml.readElement(DomainXml.java:105) [jboss-as-host-controller-7.1.2.Final-redhat-1.jar:7.1.2.Final-redhat-1]
[Host Controller]       at org.jboss.staxmapper.XMLMapperImpl.processNested(XMLMapperImpl.java:110) [staxmapper-1.1.0.Final-redhat-1.jar:1.1.0.Final-redhat-1]
[Host Controller]       at org.jboss.staxmapper.XMLMapperImpl.parseDocument(XMLMapperImpl.java:69) [staxmapper-1.1.0.Final-redhat-1.jar:1.1.0.Final-redhat-1]
[Host Controller]       at org.jboss.as.controller.persistence.XmlConfigurationPersister.load(XmlConfigurationPersister.java:133) [jboss-as-controller-7.1.2.Final-redhat-1.jar:7.1.2.Final-redhat-1]
[Host Controller]       ... 3 more
[Host Controller] 
[Host Controller] 13:30:13,827 FATAL [org.jboss.as.host.controller] (Controller Boot Thread) JBAS010933: Host Controller boot has failed in an unrecoverable manner; exiting. See previous messages for details.

```

**Comment by josejulio** [comment]
@loleary If you try to set that value using the cli and reload, the EAP server will crash and you will need to remove the handoff-executor manually from the standalone.xml file. I tried it on EAP 6.0 domain, 6.2 and 6.4 standalone.

It seems supported by the model, but not by the XSD.

**Comment by loleary** [comment]
@josejulio understood. I will defer to you for your expertise here. I just want to make sure it is clear that if it works in any version and we remove it, that will be considered a regression that we will have to fix. But, if it does not work in any version, then removing it has no ill affect.

**Comment by spinder** [comment]
LGTM.

**Pull request merged**
