### PR TITLE
BZ 1232724 - Jon32-jws-update02: EWS 2.1.0 Tomcat 7 connectors config…

### PR DESCRIPTION
**Pull request by maximebeck**
Hi there,

Can this commit please be backported to jon.3.3.x and jon.3.2.x ?

Cheers,
Maxime Beck

### CODE REVIEW

**Comment by jfclere** [comment]
@maximebeck it seems the commit contains also some formatting changing (something like tabs to spaces) would it be possible to have only the minimal changes?

**Comment by maximebeck** [comment]
@jfclere there is in fact no formatting changes, the code logic for updateResourceConfiguration is slightly different.

**Comment by jfclere** [comment]
please merge @lzoubek

**Comment by lzoubek** [comment]
cherry-picked

branch:  release/jon3.2.x
link:    https://github.com/rhq-project/rhq/commit/efeee0fdc
time:    2015-07-27 14:04:23 +0200
commit:  efeee0fdce1c964737003073ec1b426a0c75f9ba
author:  mbeck - mbeck@localhost.localdomain
message: BZ 1232724 - Jon32-jws-update02: EWS 2.1.0 Tomcat 7 connectors
         configuration change corrupts server web apps
         (cherry picked from commit
         1a0bd4c22a36b85e7fa400e73d22e9f18dff1f18) Signed-off-by: Libor
         Zoubek <lzoubek@redhat.com>

branch:  release/jon3.3.x
link:    https://github.com/rhq-project/rhq/commit/619a63a9a
time:    2015-07-27 14:05:28 +0200
commit:  619a63a9a05790b275a20693065dbee0b56f8285
author:  mbeck - mbeck@localhost.localdomain
message: BZ 1232724 - Jon32-jws-update02: EWS 2.1.0 Tomcat 7 connectors
         configuration change corrupts server web apps
         (cherry picked from commit
         1a0bd4c22a36b85e7fa400e73d22e9f18dff1f18) Signed-off-by: Libor
         Zoubek <lzoubek@redhat.com>

**Pull request merged**
