### PR TITLE
Bug 1311140 - EAP7 - missing rt filter modules for eap7

### PR DESCRIPTION
**Pull request by tsegismont**
Added new rtfilter-wfly-10-subsystem
Added new rtfilter-wfly-10-subsystem to downloads section
Fixed Web Runtime component (now at path subsystem=undertow)
Verified Calltime metric collection

### CODE REVIEW

**Comment by tsegismont** [comment]
@burmanm would you mind to review ? Thanks

**Comment by tsegismont** [comment]
@burmanm in particular, I'm interested in your opinion about the "Web Runtime" resource name. Should we keep it as is? Or change it to "Undertow Runtime"?

**Comment by pilhuhn** [comment]
On 8 Mar 2016, at 16:10, Thomas Segismont wrote:

> @burmanm in particular, I'm interested in your opinion about the "Web 
> Runtime" resource name. Should we keep it as is? Or change it to 
> "Undertow Runtime"?

Undertow is imo an implementation detail.
"Web Runtime" is generic and not the name of the previous 
implementation.

**Comment by burmanm** [comment]
Web Runtime was actually name of the previous implementation (JBossWeb runtime and indicating subsystem=web when now it is subsystem=undertow).

**Comment by loleary** [comment]
@burmanm I think @pilhuhn is still correct.

Additionally, we should avoid using community project or implementation names for resource type names. This is due to the potential they will change. 

Undertow is a web server and therefore it would make sense that we would refer to it by its function/purpose.

**Comment by burmanm** [comment]
The issue with that approach is that RHQ will still add the resource subsystem as "undertow" as it looks at the path (subsystem=undertow) and not the description saying "Web Runtime". So referring it as Web Runtime in some places, but keeping the configuration and metrics under "undertow" makes it a bit difficult in UI perspective.

That's the same reason why we don't have "messaging" subsystem with EAP7/Wildfly 10 anymore, but instead we have "messaging-activemq" there. It's just the way we're currently adding sub-resources.

**Pull request merged**
