### PR TITLE
Bug 1232847 - Increase timeout for repair operation

### PR DESCRIPTION
**Pull request by lzoubek**
Increase timeout for all long running storage node operations to 7 days.

### CODE REVIEW

**Comment by jsanda** [comment]
Check with Larry and see what he thinks about bumping up the timeout to 7 days. I'd like to get his input on this.

**Comment by lzoubek** [comment]
@loleary what do you think about bumping up the timeout to 7 days for potentially long running operations such as repair or addNodeMaintenance (which could include repair)

**Comment by loleary** [comment]
7 days is fine. Of course I am not sure how easy it will be to test this. If memory serves me right, there is some hard-coded 10 hour or 24 hour timeout for operations somewhere so I fear that this change won't do what we need it to. But I really don't know for certain.

**Comment by lzoubek** [comment]
[OperationManager](https://github.com/rhq-project/rhq/blob/master/modules/core/plugin-container/src/main/java/org/rhq/core/pc/operation/OperationManager.java#L219) defaults to 600s in case timeout is not defined within input parameters (in our case it is) or operation definition. I did not find anything about 10 or 24 hours.

**Comment by lzoubek** [comment]
retest this please

**Comment by lzoubek** [comment]
@loleary you we're right, I just tried to run an operation (which would end up after 25 hours) and it finished within ~24hours with weird result ```Failed to start : operation never started``` I'll take look at operations deeper

**Comment by lzoubek** [comment]
Bug 1265309 (preventing operations running more than 24h) fixed by 1254b9fca merging this one

**Pull request merged**
