### PR TITLE
Bug 1226413 - Implementation of rhq:handover doesn't account for EAP https connections

### PR DESCRIPTION
**Pull request by lzoubek**
Anytime plugin attempts to run CLI in connected mode, we execute  dummy CLI
command to detect whether SSL certificate needs to be accepted (manual
intervention needed). This dummy command is executed prior the original
command so we can make sure the original command is not blocked forever by
CLI asking for user input. In case we detect (based on dummy command
output), we return special implementation of ProcessExecutionResults to
caller which holds results from dummy process with error message produced by
CLI representing certificate details.

This commit does not fix 100% Bug 1226413, but  prevents blocked CLI process
as part of rhq:handover action or CLI operation.

### CODE REVIEW

**Comment by tsegismont** [comment]
I guess this is the only way to work around the issue. But this is ugly (not your fault). Can you check with EAP team if:
* there is a way to put JBoss CLI in non-interactive mode only
* or there's a property to make the certificate check fail if it's never been used before
* or there's an option to make JBoss CLI use the same truststore file as the RHQ agent?

**Comment by lzoubek** [comment]
I'll ask EAP guys what you suggest.

There is a way to make JBoss CLI use the same truststore file as RHQ agent. This can be done by editing jboss-cli.xml (default configuration file for CLI) where we can write path to truststore + password. I am not sure if it is better way, since we either need to put the password in plain text, or using vault. I can imagine we can write to jboss-cli.xml, but not sure if we're able to create vault and store truststore password in it.

**Comment by tsegismont** [comment]
Looking at the schema, there's a "modify-trust-store" option in ssl 
config which can switch off the accept certificate prompt

**Comment by lzoubek** [comment]
It is, but it does not switch the prompt off. Unfortunately this only removes the option to accept the certificate permanently.

**Comment by tsegismont** [comment]
Doh!

**Pull request merged**
