### PR TITLE
Bug 1532387 - Create child alerts for groups and templates

### PR DESCRIPTION
**Pull request by josejulio**
@burmanm can you please review?

### CODE REVIEW

**Comment by josejulio** [comment]
Updated to also create it for templates and removed the `InNewTransaction` code

**Comment by jshaughn** [comment]
I haven't looked at detail at what you're doing but certainly if you want to support group and template alert defs via the remote API it needs to call into the correct underlying services.  What caught my eye was just, "removed the InNewTransaction code".   I just want to mention that these 'InNewTransaction' services are typically there for a reason, so be very careful in any restructuring.  They are there sometimes to prevent large umbrella transactions and sometimes to ensure committed data before performing higher level work.  You may want to look at the git history to see why it's there.  I apologize in advance if you've already done that investigation, I'm just being overly cautious as many times the trasactioning work has been done to solve prior issues.

**Comment by josejulio** [comment]
Jay, Thanks for your comments.
What i meant by "removed the InNewTransaction code" is:
When starting to work on this BZ, I saw that this code was being called:
```alertDefinitionManager.createAlertDefinitionInNewTransaction```

But the `GroupDefinitionManager` and `AlertTemplateManager` don't have a similar code, at the beginning I created a method `xxxInNewTransaction` for GroupDefinitionManager because I wasn't sure if there is any special reason to have that. In the end removed that method because, `GroupDefitinionManager` calls under the hood ```alertDefinitionManager.createAlertDefinitionInNewTransaction```.

**Comment by jshaughn** [comment]
@josejulio Ah, OK, yes that makes sense.  The group/template level code typically will break the work into smaller transactions by doing exactly that, calling an 'xxxInNewTransaction' on each group member or type instance, for example.  In this way we avoid the umbrella transactions that cause timeouts or massive resource use, and commit work incrementally.  So yes, you don't want that 'inNewTransaction' type logic at the group or template level.  Thanks for the response.  We use the 'InNewTransaction' naming to easily reflect that the service/function has the non-default transaction attribute and so that callers more easily know what they are doing.

**Comment by josejulio** [comment]
@burmanm could you do a review round? is ready for merge

**Pull request merged**
